# 🏠 Arquitetura Medallion — Visão Geral (leve, sem PySpark)

Este notebook executa as 3 camadas do projeto com **pandas puro**, lendo direto os CSVs de `data/` — sem Spark, sem Java, sem MinIO/Delta.

1. **Bronze**: leitura dos CSVs brutos + `_ingested_at` + check
2. **Silver**: deduplicação, tipagem e normalização + check
3. **Gold**: 4 agregações de negócio + check

A lógica espelha os jobs oficiais (`src/ingestion/Bronze.py`, `src/processing/Silver.py`, `src/serving/Gold.py`, `src/dq/checks.py`) e vive em `src/pandas_medallion.py`.
O pipeline oficial continua em PySpark (Airflow DAG `medallion_pipeline`) — aqui é o espelho leve para explorar sem subir a stack.

> **Dados faltando?** Se `data/` estiver vazio: `python -m scripts.generate_data`
> Requer só **pandas + jupyter** (`pip install pandas jupyter`).

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))

from IPython.display import display
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

from src import pandas_medallion as med

print("pandas", pd.__version__, "| tabelas:", ", ".join(med.TABLE_NAMES))

pandas 2.2.1 | tabelas: payments, customers, orders, order_items, products, reviews

## 1. Camada BRONZE — Leitura dos CSVs brutos
Tudo como string (fiel ao `read_csv` do Spark) + coluna de auditoria `_ingested_at` em America/Sao_Paulo.

In [2]:
bronze = med.load_bronze(ROOT / "data")

print(f"{len(bronze)} tabelas carregadas")
for name, df in bronze.items():
    print(f"bronze.{name}: {len(df)} linhas x {len(df.columns)} colunas")

display(bronze["orders"].head())

6 tabelas carregadas
bronze.payments: 1800 linhas x 6 colunas
bronze.customers: 508 linhas x 7 colunas
bronze.orders: 1810 linhas x 6 colunas
bronze.order_items: 4482 linhas x 6 colunas
bronze.products: 15 linhas x 6 colunas
bronze.reviews: 1300 linhas x 7 colunas

  order_id customer_id  order_date     status total_amount                     _ingested_at
0  O000001      C00442  2025-01-22  delivered       1981.3 2026-10-07 14:28:51.505472-03:00
1  O000002      C00354  2025-07-05  delivered       881.79 2026-10-07 14:28:51.505472-03:00
2  O000003      C00446  2025-06-08    shipped     11074.68 2026-10-07 14:28:51.505472-03:00
3  O000004      C00373  2025-11-27    shipped       976.26 2026-10-07 14:28:51.505472-03:00
4  O000005      C00387  2025-10-16    shipped      1664.67 2026-10-07 14:28:51.505472-03:00

### ✔ Data Quality — Bronze
Sanidade estrutural: tabelas existem, não vazias, `_ingested_at` presente e não nulo.

In [3]:
report_bronze = med.run_dq_bronze(bronze)
print(report_bronze.summary())
display(report_bronze.failures_table())
assert report_bronze.ok, f"{len(report_bronze.errors)} erro(s) de DQ na Bronze"

DQ layer=bronze checks=24 passed=24 errors=0 warnings=0

       resultado
0  tudo passou ✔

## 2. Camada SILVER — Limpeza e Tipagem
Deduplicação por chave natural, `try_cast` (nulos quando o cast falha), normalização de texto e defaults (`"desconhecido"`, `"não informado"`).
Strings vazias contam como ausentes (nos CSVs os faltantes vêm como `""`).

In [4]:
silver = med.run_silver(bronze)

for name, df in silver.items():
    print(f"silver.{name}: {len(df)} linhas x {len(df.columns)} colunas")

display(silver["orders"].head())

silver.payments: 1800 linhas x 6 colunas
silver.customers: 500 linhas x 7 colunas
silver.orders: 1800 linhas x 6 colunas
silver.order_items: 4467 linhas x 6 colunas
silver.products: 15 linhas x 6 colunas
silver.reviews: 1300 linhas x 7 colunas

  order_id customer_id  order_date     status  total_amount                     _ingested_at
0        1         442  2025-01-22  delivered       1981.30 2026-10-07 14:28:51.505472-03:00
1        2         354  2025-07-05  delivered        881.79 2026-10-07 14:28:51.505472-03:00
2        3         446  2025-06-08    shipped      11074.68 2026-10-07 14:28:51.505472-03:00
3        4         373  2025-11-27    shipped        976.26 2026-10-07 14:28:51.505472-03:00
4        5         387  2025-10-16    shipped       1664.67 2026-10-07 14:28:51.505472-03:00

### ✔ Data Quality — Silver
PKs únicas, `rating` 1–5, domínio de `status`, referencialidade + **WARNs** de valores negativos (não bloqueiam — os CSVs contêm casos reais negativos).

In [5]:
report_silver = med.run_dq_silver(silver)
print(report_silver.summary())
display(report_silver.failures_table())
assert report_silver.ok, f"{len(report_silver.errors)} erro(s) de DQ na Silver"

DQ layer=silver checks=45 passed=42 errors=0 warnings=3

  severity              tabela                        check      detalhe
0     WARN       silver.orders   non_negative(total_amount)  1 negativos
1     WARN     silver.payments  non_negative(payment_value)  1 negativos
2     WARN  silver.order_items       non_negative(quantity)  1 negativos

## 3. Camada GOLD — Agregações de Negócio
Quatro tabelas prontas para BI (mesma semântica do Spark, inclusive o anti fan-out em `avaliacao_produto`).

In [6]:
gold = med.run_gold(silver)

for name, df in gold.items():
    print(f"gold.{name}: {len(df)} linhas x {len(df.columns)} colunas")

display(gold["vendas_por_categoria"])

gold.vendas_por_categoria: 5 linhas x 5 colunas
gold.pedidos_por_status: 4 linhas x 4 colunas
gold.avaliacao_produto: 15 linhas x 7 colunas
gold.resumo_clientes: 489 linhas x 9 colunas

      category  receita_total  itens_vendidos  produtos_distintos  total_pedidos
1  Eletrônicos     2947743.68            1922                   3            773
0         Casa      930021.76            1725                   3            700
3  Informática      790764.75            1755                   3            734
2     Esportes      522576.22            1837                   3            759
4       Livros      197035.26            1716                   3            684

### ✔ Data Quality — Gold
Métricas não nulas e `avaliacao_media` entre 1 e 5.

In [7]:
report_gold = med.run_dq_gold(gold)
print(report_gold.summary())
display(report_gold.failures_table())
assert report_gold.ok, f"{len(report_gold.errors)} erro(s) de DQ na Gold"

DQ layer=gold checks=27 passed=27 errors=0 warnings=0

       resultado
0  tudo passou ✔

## 4. Consultas nas tabelas Gold

In [8]:
print("=== Vendas por Categoria ===")
display(gold["vendas_por_categoria"])

print("=== Pedidos por Status ===")
display(gold["pedidos_por_status"])

=== Vendas por Categoria ===

      category  receita_total  itens_vendidos  produtos_distintos  total_pedidos
1  Eletrônicos     2947743.68            1922                   3            773
0         Casa      930021.76            1725                   3            700
3  Informática      790764.75            1755                   3            734
2     Esportes      522576.22            1837                   3            759
4       Livros      197035.26            1716                   3            684

=== Pedidos por Status ===

       status  total_pedidos  receita_total  ticket_medio
1   delivered           1268     3812240.22   3006.498596
3     shipped            231      715338.49   3096.703420
2  processing            204      591573.47   2899.869951
0   cancelled             97      269607.36   2779.457320

In [9]:
print("=== Top 10 Clientes por Gasto ===")
display(gold["resumo_clientes"].head(10))

=== Top 10 Clientes por Gasto ===

,customer_id,customer_name,state,city,total_pedidos,total_gasto,ticket_medio,primeiro_pedido,ultimo_pedido
216,298,Cliente 00298,RJ,Petrópolis,7,47614.81,6802.115714,2025-01-09,2025-12-27
268,344,Cliente 00344,BA,Feira de Santana,5,42090.95,8418.190000,2025-01-06,2025-12-06
193,277,Cliente 00277,DF,Brasília,5,38555.70,7711.140000,2025-05-20,2025-11-26
376,442,Cliente 00442,GO,Goiânia,8,38040.60,4755.075000,2025-01-22,2025-08-26
370,437,Cliente 00437,RJ,Petrópolis,9,37948.74,4216.526667,2025-01-03,2025-12-03
435,5,Cliente 00005,SP,São Paulo,6,35833.88,5972.313333,2025-02-25,2025-12-22
337,407,Cliente 00407,SC,Blumenau,5,35736.91,7147.382000,2025-03-31,2025-11-22
139,225,Cliente 00225,PR,Curitiba,4,35658.79,8914.697500,2025-06-10,2025-10-02
74,166,Cliente 00166,SC,Blumenau,7,35312.36,5044.622857,2025-03-26,2025-12-19
409,474,Cliente 00474,RS,Pelotas,6,34284.85,5714.141667,2025-02-04,2025-12-27

In [10]:
print("=== Receita total por status (pandas) ===")
receita_por_status = (
    gold["pedidos_por_status"]
    .groupby("status", as_index=False)
    .agg(receita=("receita_total", "sum"), pedidos=("total_pedidos", "sum"))
    .sort_values("receita", ascending=False)
)
display(receita_por_status)

=== Receita total por status (pandas) ===

       status     receita  pedidos
1   delivered  3812240.22     1268
3     shipped   715338.49      231
2  processing   591573.47      204
0   cancelled   269607.36       97

## 5. Linhagem — contagens por camada
Quantas linhas cada tabela tem em cada camada (no pipeline Spark oficial, o equivalente é o Delta history de `bronze.orders`).
A queda Bronze → Silver nos `orders` corresponde aos 10 duplicados propositais do gerador.

In [11]:
display(med.counts_table(bronze, silver, gold))

    camada                tabela  linhas
0   bronze              payments    1800
1   bronze             customers     508
2   bronze                orders    1810
3   bronze           order_items    4482
4   bronze              products      15
5   bronze               reviews    1300
6   silver              payments    1800
7   silver             customers     500
8   silver                orders    1800
9   silver           order_items    4467
10  silver              products      15
11  silver               reviews    1300
12    gold  vendas_por_categoria       5
13    gold    pedidos_por_status       4
14    gold     avaliacao_produto      15
15    gold       resumo_clientes     489

## 6. Orquestração com Airflow

Este notebook é o **espelho leve** da DAG **`medallion_pipeline`** (que roda os jobs PySpark oficiais com os checks entre as camadas):

```
bronze_ingest >> check_bronze >> silver_process >> check_silver >> gold_aggregate >> check_gold
```

```bash
podman-compose up -d --build
# UI: http://localhost:8080 (admin / admin)
podman exec medallion_airflow_scheduler airflow dags trigger medallion_pipeline
```

Agendamento: `@daily`, `catchup=False`, `max_active_runs=1` (Derby metastore não aceita escrita concorrente).
Para o pipeline oficial com Spark/Delta/MinIO, veja o README (seção Como Rodar).